<?php
$PHPR_DB_TYPE = "mysqli";
$PHPR_DB_NAME = "JEE005";
$PHPR_DB_HOST = "localhost";
$PHPR_DB_PORT = "3306";
$PHPR_DB_USER = "JEE005";
$PHPR_DB_PASS = "45172389";
$PHPR_LOAD_EXT = "";
$PHPR_TAB_PRE = "";
$PHPR_LOG = "NO";
?>